trigger:
- azure/dev
- azure/prod

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    if [ "$(Build.SourceBranch)" == "refs/heads/azure/dev" ]; then
      cp .env.development .env
      npm run build
    elif [ "$(Build.SourceBranch)" == "refs/heads/azure/prod" ]; then
      cp .env.production .env
      npm run build
    fi
  displayName: 'Replace .env file and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'drop'
    publishLocation: 'pipeline'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    api_location: ''
    output_location: 'dist'
    azure_static_web_apps_api_token: $(azure_static_web_apps_api_token)
